### PR TITLE
Merge cpp into header

### LINKED ISSUE #4: How to use DEBUG_PING ?
i don't know use DEBUG_PING

### PR DESCRIPTION
**Pull request by micooke**
To resolve #4 
* Contents merged from ESP8266Ping.cpp into ESP8266.h
* commented out pin_opt inside _ping_recv_cb() as it is not (currently) used

### CODE REVIEW

**Comment by dancol90** [comment]
I would rather leave the two file, rename the cpp one in something like .cpp.impl or .hxx, and include it in the header file.
This way we could achieve the same thing, leaving declaration and implementation separated!

Hoping that the Arduino IDE permits it without messing everything up 😂

**Comment by micooke** [comment]
It's your party :smile: But can i suggest having two header files - one for your class prototype, the other for your implementation (obviously include the implementation in your prototype).

That way you are using standard c/c++ files, and syntax highlighting etc work

**Comment by dancol90** [comment]
Most editors recognize extensions like `.hxx`, `.inl`, etc.
Maybe we can use something like `.impl.h` to distinguish it from the declaration

**Comment by dancol90** [comment]
Fixed by c5f0be4

**Pull request closed without merging**
